import 'package:flutter/material.dart';

class LocalizationService {
  static const String defaultLanguage = 'tr';
  
  static final Map<String, Map<String, String>> _translations = {
    'tr': {
      'app_name': 'Eyes On Campus',
      'tagline': 'ÜNİVERSİTE SOSYAL AĞI',
      'get_started': 'Başla',
      'already_have_account': 'Zaten Hesabım Var',
      'seed_demo_data': '🛠 Apple Demo Verilerini Yükle',
      'email_label': 'Üniversite E-postan',
      'email_hint': 'ad.soyad@uni.edu.tr',
      'email_desc': 'Sadece kampüsteki gerçek öğrencilerin olduğundan emin olmak için .edu.tr uzantılı e-postana ihtiyacımız var.',
      'password_label': 'Hesap Şifresi',
      'password_hint': 'Şifreniz',
      'password_desc': 'Lütfen giriş yapmak için bir şifre belirle.',
      'complete_profile': 'Profili Tamamla',
      'profile_desc': 'Kampüsteki arkadaşların seni bu isimle görecek.',
      'full_name': 'Ad Soyad',
      'dept': 'Bölüm',
      'class': 'Sınıf',
      'accept_terms': 'Kullanım Şartları (EULA)',
      'accept_privacy': 'Gizlilik Politikasını',
      'and': ' ve ',
      'accept_desc': ' okudum ve kabul ediyorum.',
      'complete_reg': 'Kaydı Tamamla',
      'login_title': 'Giriş Yap',
      'login_email_hint': 'E-posta (örn: test@eyesoncampus.com)',
      'login_pass_hint': 'Şifre',
      'cancel': 'İptal',
      'login_btn': 'Giriş',
      'legal_agree_prefix': 'Hüküm ve Koşulları, ',
      'legal_agree_suffix': ' ve topluluk kurallarını kabul ediyorum. Uygunsuz içeriğe sıfır tolerans gösterildiğini anlıyorum.',
      'age_confirm': '18 yaşından büyük olduğumu ve bir üniversite öğrencisi olduğumu beyan ederim.',
      // Home
      'venues': 'MEKANLAR',
      'people_here': 'kişi burada',
      'discovery': 'Keşfet',
      'notifications': 'Bildirimler',
      'chat': 'Sohbet',
      'profile': 'Profil',
      'university': 'Üniversite',
      'select_university': 'Üniversite Seç',
      // Discover
      'no_one_left': 'Yakınında kimse kalmadı.',
      'refresh': 'Yenile',
      // Chat
      'search_chat': 'Mesajlarda ara...',
      'no_chat_found': 'Henüz mesajınız yok.',
      'type_message': 'Mesaj yaz…',
      'onboarding_title_1': 'Kampüsü Keşfet',
      'onboarding_desc_1': 'Kütüphane, kafe veya etkinlikler...\nAynı kampüsü paylaştığın\nöğrencilerle tanış.',
      'onboarding_title_2': 'Buzları\nEritin',
      'onboarding_desc_2': 'Kampüste dikkatinizi çeken\nkişilere anonim olarak\nilginizi belli edin.',
      'onboarding_title_3': 'Onaylı Öğrenci\nTopluluğu',
      'onboarding_desc_3': 'Sadece .edu e-postasıyla üye\nolunabilir. Kampüsünüzdeki gerçek\nkişilerle güvenle tanışın.',
      'onboarding_title_4': 'Tamamen\nGüvenli',
      'onboarding_desc_4': 'Sen onaylamadan kimse sana\nmesaj atamaz. Sadece karşılıklı\nilgiyle mesajlaşma başlar.',
      'onboarding_start': 'HADİ BAŞLAYALIM',
      'onboarding_next': 'İLERİ →',
      'onboarding_skip': 'GEÇ',
      // Settings
      'settings': 'Ayarlar',
      'edit_profile': 'Profili Düzenle',
      'university_verify': 'Üniversite Doğrulama',
      'verified': '✓ Doğrulandı',
      'privacy': 'Gizlilik',
      'visibility_range': 'Görünürlük Menzili',
      'blocked': 'Engellenmiş',
      'blocked_desc': 'Engellediğin kişileri yönet',
      'campus_diary': 'Kampüs Günlüğü',
      'add_photo': 'Fotoğraf Ekle',
      'add_interest': 'İlgi Ekle',
      'max_photos_reached': 'Maksimum 6 fotoğrafa ulaştın.',
      'notifs': 'Bildirimler',
      'look_notif': 'Bakış Bildirimi',
      'match_notif': 'Bağlantı Bildirimi',
      'general': 'Genel',
      'contact_us': 'Bize Ulaşın / Destek',
      'privacy_policy': 'Gizlilik Politikası',
      'eula': 'Kullanım Şartları (EULA)',
      'logout': 'Çıkış Yap',
      'delete_account': 'Hesabımı Sil',
      // Notifications
      'new_match': 'Yeni Bağlantı',
      'match_msg': 'ile bağlantı kurdunuz! Sohbet başlatabilirsiniz.',
      'look_msg': 'Biri sana baktı! Sen de bakıyor musun?',
      // Details
      'anon_user': 'Anonim Kullanıcı',
      'hidden_until_match': 'BAĞLANTIYA KADAR GİZLİ',
      'anon_desc': 'Bu kişi anonim modda.\nBağlantı kurarsanız profil açılır.',
      'tips': 'İpuçları',
      'location': 'Konum',
      'block_user': 'Kullanıcıyı Engelle',
      'report_user': 'Kullanıcıyı Bildir',
      'send_interest': 'Bakış At',
      'interest_sent': 'Göz kırpıldı!',
      'save': 'Kaydet',
      'profile_updated': 'Profil güncellendi!',
      'profile_error': 'Profil güncellenirken bir hata oluştu.',
      'just_now': 'az önce',
      'matched_with': 'ile bağlantı kurdunuz!',
      'start_chat': 'Sohbet başlatabilirsiniz.',
      'looks': 'Bakış',
      'matches': 'Bağlantı',
      'chats': 'Sohbet',
      'same_venue_error': 'Sadece aynı konumda olduğunuz kişilere göz kırpabilirsiniz.',
      'must_checkin': 'Göz kırpabilmek için önce giriş (check-in) yapmalısın!',
      'weeks': 'Hafta',
      'interests': 'İlgi Alanları',
      'visibility': 'Görünürlük',
      'show_on_radar': 'Radar\'da Görün',
      'radar_desc': 'Çevredekiler seni görür',
      'share_location': 'Konum Paylaş',
      'location_desc': 'Hangi mekândasın',
      'upcoming_events': 'Yaklaşan Etkinlikler',
      'joined_events': 'Katıldıklarım',
      'search_events': 'Etkinlik ara...',
      // Profile & Other Profile
      'bio': 'Biyografi',
      'interest_areas': 'İlgi Alanları',
      'currently_here': 'Şu an burada',
      'waiting': 'Bekleniyor...',
      'im_looking_at_you': '👁️ Göz Kırp!',
      'chat_with': '💬 Sohbet Et',
      'no_chats_yet': 'Henüz sohbetin yok.',
      'account': 'Hesap',
      'profile_name_desc': 'İsim, fotoğraf, ilgi alanları',
      'edu_email': '@edu.tr e-posta',
      'edu_verified': 'Üniversite e-postanız zaten onaylandı.',
      'radar_area': 'Radar alanı',
      'range_locked': 'Menzil ayarı şu anda değiştirilemez.',
      'no_blocked': 'Engellenmiş kullanıcınız bulunmuyor.',
      'blocked_count': 'kişi',
      // Events
      'events_title': 'Etkinlik',
      'live': 'CANLI',
      'join': 'KATIL',
      'event_people': 'BU ETKİNLİKTE OLANLAR',
      'other_events': 'DİĞER ETKİNLİKLER',
      'event_mode': 'E T K İ N L İ K   M O D U',
      // Reports
      'report_title': 'Şikayet Et',
      'report_reason': 'Lütfen şikayet nedeninizi seçin:',
      'report_inappropriate': 'Uygunsuz İçerik veya Profil',
      'report_spam': 'Spam veya Dolandırıcılık',
      'report_harassment': 'Rahatsız Edici Davranış / Taciz',
      'report_fake': 'Sahte Profil / Diğer',
      'report_received': 'Şikayetiniz alındı. İnceleme başlatıldı.',
      // Nearby
      'nearby': 'YAKININDA',
      'people': 'kişi',
      'radar': 'Radar',
      'events': 'Etkinlik',
    },
    'en': {
      'app_name': 'Eyes On Campus',
      'tagline': 'UNIVERSITY SOCIAL NETWORK',
      'get_started': 'Get Started',
      'already_have_account': 'Already Have an Account',
      'seed_demo_data': '🛠 Seed Apple Demo Data',
      'email_label': 'University Email',
      'email_hint': 'name.surname@uni.edu.tr',
      'email_desc': 'We need your .edu.tr email to ensure you are a real student on campus.',
      'password_label': 'Account Password',
      'password_hint': 'Your balance',
      'password_desc': 'Please set a password for your account.',
      'complete_profile': 'Complete Profile',
      'profile_desc': 'Your friends on campus will see you with this name.',
      'full_name': 'Full Name',
      'dept': 'Department',
      'class': 'Class/Year',
      'accept_terms': 'Terms of Use (EULA)',
      'accept_privacy': 'Privacy Policy',
      'and': ' and ',
      'accept_desc': ' I have read and accept.',
      'complete_reg': 'Complete Registration',
      'login_title': 'Login',
      'login_email_hint': 'Email (e.g: test@eyesoncampus.com)',
      'login_pass_hint': 'Password',
      'cancel': 'Cancel',
      'login_btn': 'Login',
      'legal_agree_prefix': 'I agree to the Terms, ',
      'legal_agree_suffix': ' and community rules. I understand there is zero tolerance for objectionable content.',
      'age_confirm': 'I confirm that I am over 18 and a university student.',
      // Home
      'venues': 'VENUES',
      'people_here': 'people here',
      'discovery': 'Discover',
      'notifications': 'Notifs',
      'chat': 'Chat',
      'profile': 'Profile',
      'university': 'University',
      'select_university': 'Select University',
      // Discover
      'no_one_left': 'No one left nearby.',
      'refresh': 'Refresh',
      // Chat
      'search_chat': 'Search messages...',
      'no_chat_found': 'No messages yet.',
      'type_message': 'Type a message...',
      'onboarding_title_1': 'Discover Your\nCampus',
      'onboarding_desc_1': 'Library, cafe, or events...\nMeet students who share\nthe same campus with you.',
      'onboarding_title_2': 'Break the\nIce',
      'onboarding_desc_2': 'Anonymously show interest\nto people who catch your\nattention on campus.',
      'onboarding_title_3': 'Verified Student\nCommunity',
      'onboarding_desc_3': 'Exclusive to .edu addresses.\nConnect safely with verified\npeers from your university.',
      'onboarding_title_4': 'Completely\nSafe',
      'onboarding_desc_4': 'No one can message you\nwithout your approval. Chat\nstarts only on mutual interest.',
      'onboarding_start': "LET'S START",
      'onboarding_next': 'NEXT →',
      'onboarding_skip': 'SKIP',
      // Settings
      'settings': 'Settings',
      'edit_profile': 'Edit Profile',
      'university_verify': 'University Verification',
      'verified': '✓ Verified',
      'privacy': 'Privacy',
      'visibility_range': 'Visibility Range',
      'blocked': 'Blocked Users',
      'blocked_desc': 'Manage blocked users',
      'campus_diary': 'Campus Diary',
      'add_photo': 'Add Photo',
      'add_interest': 'Add Interest',
      'max_photos_reached': 'Max 6 photos reached.',
      'notifs': 'Notifications',
      'look_notif': 'Look Notification',
      'match_notif': 'Connection Notification',
      'general': 'General',
      'contact_us': 'Contact Us / Support',
      'privacy_policy': 'Privacy Policy',
      'eula': 'Terms of Use (EULA)',
      'logout': 'Logout',
      'delete_account': 'Delete My Account',
      // Notifications
      'new_match': 'New Connection',
      'match_msg': 'connected with you! You can start a chat.',
      'look_title': 'Eye Contact',
      'look_msg': 'Someone looked at you! Are you looking back?',
      'nearby': 'NEARBY',
      'discover_campus': 'Discover Campus',
      'people': 'people',
      'radar': 'Radar',
      'events': 'Events',
      // Details
      'anon_user': 'Anonymous User',
      'hidden_until_match': 'HIDDEN UNTIL CONNECTED',
      'anon_desc': 'This user is in anonymous mode.\nProfile opens if you connect.',
      'tips': 'Hints',
      'location': 'Location',
      'block_user': 'Block User',
      'report_user': 'Report User',
      'send_interest': 'Send Look',
      'interest_sent': 'Look Sent',
      'save': 'Save',
      'profile_updated': 'Profile updated!',
      'profile_error': 'An error occurred while updating profile.',
      'just_now': 'just now',
      'matched_with': 'connected with you!',
      'start_chat': 'You can start a chat.',
      'looks': 'Looks',
      'matches': 'Connections',
      'chats': 'Chats',
      'same_venue_error': 'You can only wink at people in the same venue.',
      'must_checkin': 'You must check-in before winking!',
      'weeks': 'Weeks',
      'interests': 'Interests',
      'visibility': 'Visibility',
      'show_on_radar': 'Show on Radar',
      'radar_desc': 'Others can see you',
      'share_location': 'Share Location',
      'location_desc': 'Current venue visibility',
      'upcoming_events': 'Upcoming Events',
      'joined_events': 'Joined',
      'search_events': 'Search events...',
      // Profile & Other Profile
      'bio': 'Biography',
      'interest_areas': 'Interests',
      'currently_here': 'Currently here',
      'waiting': 'Waiting...',
      'im_looking_at_you': '� Wink!',
      'chat_with': '💬 Chat',
      'no_chats_yet': 'No chats yet.',
      'account': 'Account',
      'profile_name_desc': 'Name, photo, interests',
      'edu_email': '@edu.tr email',
      'edu_verified': 'Your university email is already verified.',
      'radar_area': 'Radar area',
      'range_locked': 'Range setting cannot be changed at this time.',
      'no_blocked': 'No blocked users.',
      'blocked_count': 'users',
      // Events
      'events_title': 'Events',
      'live': 'LIVE',
      'join': 'JOIN',
      'event_people': 'PEOPLE AT THIS EVENT',
      'other_events': 'OTHER EVENTS',
      'event_mode': 'E V E N T   M O D E',
      // Reports
      'report_title': 'Report',
      'report_reason': 'Please select a reason:',
      'report_inappropriate': 'Inappropriate Content or Profile',
      'report_spam': 'Spam or Fraud',
      'report_harassment': 'Harassing Behavior',
      'report_fake': 'Fake Profile / Other',
      'report_received': 'Your report has been received. Investigation started.',
    }
  };

  static String translate(String key, String lang) {
    return _translations[lang]?[key] ?? key;
  }
}

extension TranslateString on String {
  String tr(BuildContext context) {
    // We will get current language from a provider
    return this; 
  }
}
